// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import "INativeModule.idl";
import "ReactContext.idl";

namespace Microsoft.ReactNative
{
  [webhosthidden]
  interface IReactPackage
  {
	  IVectorView<INativeModule> CreateNativeModules(ReactContext reactContext);
  };
}
