// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import "INativeModule.idl";

namespace Microsoft.ReactNative.Bridge {
  [default_interface]
  runtimeclass Promise {
    Promise(MethodDelegate resolve, MethodDelegate reject);
    void Resolve(IInspectable value);
    void Reject(String code, String message, String stack, IInspectable value);
  }
}
