// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import "INativeModule.idl";

namespace Microsoft.ReactNative.Bridge
{
	interface IReactInstance
	{
		IIterable<INativeModule> NativeModules { get; };
		void InvokeFunction(String moduleName, String method, IVectorView<IInspectable> arguments, String tracingName);
		void InvokeCallback(Int32 callbackId, IVectorView<IInspectable> arguments);
	};

  [webhosthidden]
  [default_interface]
  runtimeclass ReactInstance : IReactInstance
  {
  };
}
