import "INativeModule.idl";

namespace Microsoft.ReactNative
{
	interface IReactInstance
	{
		IIterable<INativeModule> NativeModules { get; };
		void InvokeFunction(String moduleName, String method, Windows.Data.Json.JsonArray arguments, String tracingName);
		void InvokeCallback(Int32 callbackId, Windows.Data.Json.JsonArray arguments);
	};
}

namespace Microsoft.ReactNative.Bridge
{
    [webhosthidden]
  	[default_interface]
    runtimeclass ReactInstance : Microsoft.ReactNative.IReactInstance
    {
    }
}
