import "ReactInstance.idl";
import "INativeModule.idl";

namespace Microsoft.ReactNative
{
    [webhosthidden]
    runtimeclass ReactContext
    {
        IReactInstance ReactInstance { get; };
    }
}
