import "IReactPackage.idl";
import "INativeModule.idl";
import "ReactInstanceManager.idl";
import "ReactRootView.idl";

namespace Microsoft.React
{
  [webhosthidden]
  delegate void OnResumeAction();

  [webhosthidden]
  [default_interface]
  unsealed runtimeclass ReactNativeHost
  {
    ReactNativeHost();

    ReactInstanceManager ReactInstanceManager{ get; };

    Boolean HasInstance{ get; };

    overridable IVectorView<IReactPackage> Packages{ get; };

    overridable String MainComponentName{ get; };
    overridable Boolean UseDeveloperSupport{ get; };
    overridable String JavaScriptMainModuleName{ get; };
    overridable String JavaScriptBundleFile{ get; };

    Windows.UI.Xaml.UIElement OnCreate();

    void OnSuspend();
    void OnEnteredBackground();
    void OnLeavingBackground();
    void OnResume(OnResumeAction action);
  };
}
